#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Esoftuz\Framework\App;
use Esoftuz\Framework\Exceptions\CommandNotFoundException;

$args = get_args();

try {
    $app = new App(__DIR__);
    $app->handle($args);
} catch (CommandNotFoundException $e) {
    echo abort($e->getCode(), $e->getMessage());
}